version: '3'
services:
  speech-synthesis-server:
    image: r8.im/suno-ai/bark@sha256:8418ea81741ac6f5ae6f9c4a2bd6adc4c9208b6d31be5fcfa4313e054aebd12d
    ports:
      - "9000:5000"
    # If you have a working nvidia GPU, speech synthesis can be ran on that for a performance boost
    # runtime: nvidia
    container_name: speech-synthesis-server

  speech-recognition-server:
    build:
      context: ./whisper.api
    ports:
      - "9001:7860"
    container_name: speech-recognition-server
    environment:
      # BuildKit has to be disabled because of Conflict
      - COMPOSE_DOCKER_CLI_BUILD=0

  postgres:
      image: postgres:latest
      container_name: speech-recognition-server-db 
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      ports:
      - '5432:5432'
      volumes:
      - ./whisper-postgres-db:/var/lib/postgresql/data

  conversational-agent-server:
    build:
      context: ./rasa-bot
    ports:
      - "9002:5005"
    volumes:
      - ./rasa-bot/models/:/app/models/:rw
      - ./rasa-bot/data/:/app/data/
      - ./rasa-bot/config.yml:/app/config.yml
      - ./rasa-bot/actions/:/app/actions/
    command: 
      - train 
    container_name: conversational-agent-server
    # RAM limit need a little bump for building Rasa
    deploy:
      resources:
        limits:
          memory: '512M'
    
  webui-server:
    build:
      context: ./web-ui
    ports:
      - "8080:80"
    volumes:
      - ./web-db:/web-db
    container_name: webui-server

  