version: '3'
services:
  speech-synthesis-server:
    image: r8.im/suno-ai/bark
    ports:
      - "9000:5000"
    runtime: nvidia
    container_name: speech-synthesis-server

  speech-recognition-server:
    build:
      context: ./whisper.api
    ports:
      - "9001:7860"
    container_name: speech-recognition-server
    environment:
      # BuildKit has to be disabled because of Conflict
      - COMPOSE_DOCKER_CLI_BUILD=0
      - ALGORITHM="idk"
      - SERVER_NAME="whisper-server"
      - SECRET_KEY="idk"
      - SERVER_HOST="/"
      - POSTGRES_DATABASE_URL="idk"

  conversational-agent-server:
    build:
      context: ./rasa-bot
    ports:
      - "9002:5005"
    volumes:
      - ./rasa-bot/models/:/app/models/:rw
      - ./rasa-bot/data/:/app/data/
      - ./rasa-bot/config.yml:/app/config.yml
      - ./rasa-bot/actions/:/app/actions/
    command: 
      - train 
    container_name: conversational-agent-server
    # RAM limit need a little bump for building Rasa
    deploy:
      resources:
        limits:
          memory: '512M'
    
  webui-server:
    build:
      context: ./web-ui
    image: web-ui-server
    ports:
      - "8080:80"
    volumes:
      - ./web-db:/web-db
    container_name: webui-server

  