version: '3'
services:
  # speech-synthesis-server:
  #   image: r8.im/suno-ai/bark@sha256:8418ea81741ac6f5ae6f9c4a2bd6adc4c9208b6d31be5fcfa4313e054aebd12d
  #   ports:
  #     - "9000:5000"
  #   # If you have a working nvidia GPU, speech synthesis can be ran on that for a performance boost
  #   # runtime: nvidia
  #   container_name: speech-synthesis-server

  speech-synthesis-server:
    image: mycroftai/mimic3:latest
    ports:
      - "59125:59125"
    # If you have a working nvidia GPU, speech synthesis can be ran on that for a performance boost
    # runtime: nvidia
    volumes:
    - ./mimic3:/home/mimic3/.local/share/mycroft/mimic3
    container_name: speech-synthesis-server
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
          
  speech-recognition-server:
    build:
      context: ./whisper.api
    ports:
      - "9001:7860"
    container_name: speech-recognition-server
    environment:
      # BuildKit has to be disabled because of Conflict
      - COMPOSE_DOCKER_CLI_BUILD=0
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M

  postgres:
    image: postgres:latest
    container_name: speech-recognition-server-db 
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    ports:
    - '5432:5432'
    volumes:
    - ./whisper-postgres-db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  conversational-agent-server:
    build:
      context: ./rasa-bot
    restart: "always"
    networks:
      - ca_network
    ports:
      - 5005:5005
    volumes:
      - ./rasa-bot/models/:/app/models/:rw
      - ./rasa-bot/data/:/app/data/
      - ./rasa-bot/config.yml:/app/config.yml:rw
      - ./rasa-bot/endpoints.yml:/app/endpoints.yml:rw
    command: 
    - "run"
    container_name: conversational-agent-server
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  conversational-agent-action-server:
    build:
      context: ./rasa-bot
    restart: "always"
    networks:
      - ca_network
    ports:
      - 5055:5055
    volumes:
      - ./rasa-bot/models/:/app/models/:rw
      - ./rasa-bot/data/:/app/data/
      - ./rasa-bot/config.yml:/app/config.yml
      - ./rasa-bot/endpoints.yml:/app/endpoints.yml
      - ./rasa-bot/actions/:/app/actions/
    command: 
      - run
      - actions
    container_name: conversational-agent-action-server
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

              
  webui-server:
    build:
      context: ./web-ui
    ports:
      - "8080:80"
    volumes:
      - ./web-db:/web-db
    container_name: webui-server
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


networks:
  ca_network:
    driver: bridge

  